# Generated by Django 6.0.6 on 2026-07-02 20:59

import apps.menu.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Digital Menu', max_length=100, verbose_name='اسم المنيو')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='وصف مختصر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='menu/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.menu.models.validate_image_size], verbose_name='الشعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المنيو',
                'verbose_name_plural': 'إعدادات المنيو',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('slug', models.SlugField(help_text='مثال: breakfast أو coffee أو dessert', max_length=120, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.category_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.menu.models.validate_image_size], verbose_name='صورة القسم')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب الظهور')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='إظهار القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='menu_catego_slug_6d0e16_idx'), models.Index(fields=['is_active', 'display_order'], name='menu_catego_is_acti_afc8ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان الصورة')),
                ('image', models.ImageField(upload_to=apps.menu.models.menu_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.menu.models.validate_image_size], verbose_name='صورة المنيو')),
                ('alt_text', models.CharField(blank=True, help_text='وصف مختصر للصورة لتحسين الوصول وتجربة المستخدم.', max_length=150, verbose_name='وصف الصورة')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب الصورة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='إظهار الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='menu.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'صورة منيو',
                'verbose_name_plural': 'صور المنيو',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='menu_menuim_categor_159619_idx'), models.Index(fields=['display_order'], name='menu_menuim_display_051185_idx')],
            },
        ),
    ]
