# Generated by Django 6.0.6 on 2026-07-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimage',
            name='allergens',
            field=models.CharField(blank=True, max_length=200, verbose_name='مسببات الحساسية'),
        ),
        migrations.AddField(
            model_name='menuimage',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='السعرات الحرارية'),
        ),
        migrations.AddField(
            model_name='menuimage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='السعر'),
        ),
    ]
