# Generated by Django 6.0.6 on 2026-07-07 03:07

import apps.menu.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuimage_allergens_menuimage_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.menu.models.validate_image_size], verbose_name='صورة القسم'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[apps.menu.models.validate_image_size], verbose_name='صورة المنيو'),
        ),
        migrations.AlterField(
            model_name='menusettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.menu.models.validate_image_size], verbose_name='الشعار'),
        ),
    ]
