# Generated by Django 6.0.6 on 2026-07-07 17:33

import apps.menu.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_image_alter_menuimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuimage',
            options={'ordering': ['display_order', 'created_at'], 'verbose_name': 'منتج منيو', 'verbose_name_plural': 'منتجات المنيو'},
        ),
        migrations.AddField(
            model_name='menuimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='menuimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم المنتج بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='allergens',
            field=models.CharField(blank=True, help_text='مثال: قمح / جلوتين، حليب / لاكتوز، بيض', max_length=250, verbose_name='مسببات الحساسية'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='اكتب الرقم فقط، مثال: 581', null=True, verbose_name='السعرات الحرارية'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتيب المنتج'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[apps.menu.models.validate_image_size], verbose_name='صورة المنتج / صورة المنيو'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='إظهار المنتج'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم المنتج بالعربي'),
        ),
    ]
